
-include config.mak

# default user-configurable settings (override in config.mak)
CC = $(CROSS)gcc
CONFIG_ARCH ?= powerpc
CONFIG_OS ?= linux
CONFIG_TRANSPORT ?= shm


# derived settings for more convenient Makefile syntax
CONFIG_GCC = $(if $(findstring gcc,$(CC)),y,)
CONFIG_POWERPC = $(if $(findstring powerpc,$(CONFIG_ARCH)),y,)
CONFIG_ARM = $(if $(findstring arm,$(CONFIG_ARCH)),y,)
CONFIG_LINUX = $(if $(findstring linux,$(CONFIG_OS)),y,)
CONFIG_SHM = $(if $(findstring shm,$(CONFIG_TRANSPORT)),y,)
