#!/usr/bin/env python

def options(opt):
	opt.add_option('--linuxdir', help='Directory to Linux kernel which has had \'make modules_prepare\' run.')
	opt.add_option('--linuxargs', help='Extra options to pass to the Linux kernel module build system.')

def configure(conf):
	conf.env.LINUXDIR = conf.options.linuxdir
	conf.env.LINUXARGS = conf.options.linuxargs

def build(bld):
	includes = [
		'.',
		'../include',
		'../../include',
		'../../include/%s' % bld.env.OS,
		'../include/arch/%s' % bld.env.ARCH,
	]

	sources = [
		'shm.c'
	]

	extra_sources = {
		'linux': ['linux/shm_os.c'],
	}

	sources += extra_sources.get(bld.env.OS, [])

	bld.stlib(
		target='mcapi_shm',
		source=' '.join(sources),

		includes=' '.join(includes),
		cflags='-O2 -Wall',
	)

# XXX build kmod
