#!/usr/bin/env python

def build(bld):
	includes = [
		'.',
		'../include',
		'../../include',
		'../../include/%s' % bld.env.OS,
		'../include/arch/%s' % bld.env.ARCH,
	]

	sources = [
		'shm.c'
	]

	extra_sources = {
		'linux': ['linux/shm_os.c'],
	}

	sources += extra_sources.get(bld.env.OS, [])

	bld.stlib(
		target='mcapi_shm',
		source=' '.join(sources),

		includes=' '.join(includes),
		cflags='-O2 -Wall',
	)

# XXX build kmod
